"""Typed models for the Agentic Search v2 orchestration loop."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any, Dict, Iterable, List, Literal, Mapping, Optional

QueryType = Literal["semantic", "keyword"]
ActionType = Literal["search", "expand"]


class StopReason(str, Enum):
    """Machine-readable reason why an agentic search stopped."""

    SUFFICIENT_EVIDENCE = "sufficient_evidence"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"
    TOKEN_BUDGET_EXHAUSTED = "token_budget_exhausted"
    ITERATION_LIMIT_REACHED = "iteration_limit_reached"
    QUERY_LIMIT_REACHED = "query_limit_reached"
    NO_PROGRESS = "no_progress"
    NO_RESULTS = "no_results"
    INVALID_ASSESSMENT = "invalid_assessment"


@dataclass(slots=True, frozen=True)
class SearchQuery:
    """A validated search request generated by an LLM or fallback planner."""

    query: str
    type: QueryType = "semantic"
    rationale: Optional[str] = None

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any]) -> Optional["SearchQuery"]:
        query = value.get("query")
        if not isinstance(query, str) or not query.strip():
            return None
        raw_type = value.get("type", "semantic")
        query_type: QueryType = "keyword" if raw_type == "keyword" else "semantic"
        rationale = value.get("rationale")
        return cls(
            query=query.strip(),
            type=query_type,
            rationale=rationale.strip() if isinstance(rationale, str) and rationale.strip() else None,
        )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(slots=True, frozen=True)
class RetrievalAction:
    """A bounded next action proposed by evidence assessment."""

    type: ActionType
    query: Optional[str] = None
    query_type: QueryType = "semantic"
    source_ids: List[str] = field(default_factory=list)
    relationship_types: List[str] = field(default_factory=lambda: ["PREVIOUS", "NEXT"])
    rationale: Optional[str] = None

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any]) -> Optional["RetrievalAction"]:
        raw_type = value.get("type", "search")
        action_type: ActionType = "expand" if raw_type == "expand" else "search"
        rationale = value.get("rationale")
        if action_type == "search":
            query = value.get("query")
            if not isinstance(query, str) or not query.strip():
                return None
            raw_query_type = value.get("query_type", value.get("queryType", "semantic"))
            query_type: QueryType = "keyword" if raw_query_type == "keyword" else "semantic"
            return cls(
                type="search",
                query=query.strip(),
                query_type=query_type,
                rationale=rationale.strip() if isinstance(rationale, str) and rationale.strip() else None,
            )

        raw_ids = value.get("source_ids", value.get("sourceIds", []))
        source_ids = [str(item) for item in raw_ids if item] if isinstance(raw_ids, list) else []
        if not source_ids:
            return None
        raw_relationships = value.get(
            "relationship_types",
            value.get("relationshipTypes", ["PREVIOUS", "NEXT"]),
        )
        relationship_types = (
            [str(item).upper() for item in raw_relationships if item]
            if isinstance(raw_relationships, list)
            else ["PREVIOUS", "NEXT"]
        )
        return cls(
            type="expand",
            source_ids=source_ids,
            relationship_types=relationship_types or ["PREVIOUS", "NEXT"],
            rationale=rationale.strip() if isinstance(rationale, str) and rationale.strip() else None,
        )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class EvidenceProvenance:
    """How and when an evidence chunk entered the candidate pool."""

    queries: List[str] = field(default_factory=list)
    query_types: List[QueryType] = field(default_factory=list)
    iterations: List[int] = field(default_factory=list)
    ranks: List[int] = field(default_factory=list)
    original_scores: List[Optional[float]] = field(default_factory=list)
    expanded_from: List[str] = field(default_factory=list)
    fusion_score: float = 0.0

    def add_retrieval(
        self,
        *,
        query: str,
        query_type: QueryType,
        iteration: int,
        rank: int,
        score: Optional[float],
    ) -> None:
        self.queries.append(query)
        self.query_types.append(query_type)
        self.iterations.append(iteration)
        self.ranks.append(rank)
        self.original_scores.append(score)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class EvidenceItem:
    """Compact evidence passed to the LLM assessor."""

    id: str
    text: str
    rank: int
    score: Optional[float] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class CoverageItem:
    """Assessment of one sub-question or evidence requirement."""

    requirement: str
    covered: bool
    supporting_source_ids: List[str] = field(default_factory=list)
    note: Optional[str] = None

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any]) -> Optional["CoverageItem"]:
        requirement = value.get("requirement")
        covered = value.get("covered")
        if not isinstance(requirement, str) or not requirement.strip() or not isinstance(covered, bool):
            return None
        raw_ids = value.get("supporting_source_ids", value.get("supportingSourceIds", []))
        ids = [str(item) for item in raw_ids if item] if isinstance(raw_ids, list) else []
        note = value.get("note")
        return cls(
            requirement=requirement.strip(),
            covered=covered,
            supporting_source_ids=ids,
            note=note.strip() if isinstance(note, str) and note.strip() else None,
        )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class EvidenceAssessment:
    """Structured, fail-closed assessment of the current evidence set."""

    answerable: bool
    confidence: float = 0.0
    coverage: List[CoverageItem] = field(default_factory=list)
    missing_information: List[str] = field(default_factory=list)
    contradictions: List[str] = field(default_factory=list)
    supporting_source_ids: List[str] = field(default_factory=list)
    next_actions: List[RetrievalAction] = field(default_factory=list)
    rationale: Optional[str] = None
    valid: bool = True

    @classmethod
    def from_mapping(
        cls,
        value: Mapping[str, Any],
        *,
        valid_source_ids: Optional[Iterable[str]] = None,
    ) -> "EvidenceAssessment":
        answerable = value.get("answerable", value.get("canAnswer"))
        if not isinstance(answerable, bool):
            return cls(answerable=False, valid=False, rationale="Assessment did not contain a boolean answerable field.")

        raw_confidence = value.get("confidence", 1.0 if answerable else 0.0)
        confidence = float(raw_confidence) if isinstance(raw_confidence, (int, float)) else 0.0
        confidence = max(0.0, min(1.0, confidence))

        raw_coverage = value.get("coverage", [])
        coverage: List[CoverageItem] = []
        if isinstance(raw_coverage, list):
            for raw in raw_coverage:
                parsed_coverage = CoverageItem.from_mapping(raw) if isinstance(raw, Mapping) else None
                if parsed_coverage is not None:
                    coverage.append(parsed_coverage)
        raw_actions = value.get("next_actions", value.get("nextActions", []))
        actions: List[RetrievalAction] = []
        if isinstance(raw_actions, list):
            for raw in raw_actions:
                parsed_action = RetrievalAction.from_mapping(raw) if isinstance(raw, Mapping) else None
                if parsed_action is not None:
                    actions.append(parsed_action)

        allowed_ids = set(valid_source_ids) if valid_source_ids is not None else None

        def _strings(key: str, camel_key: Optional[str] = None) -> List[str]:
            raw = value.get(key, value.get(camel_key, [])) if camel_key else value.get(key, [])
            return [str(item) for item in raw if item] if isinstance(raw, list) else []

        supporting_ids = _strings("supporting_source_ids", "supportingSourceIds")
        if allowed_ids is not None:
            supporting_ids = [source_id for source_id in supporting_ids if source_id in allowed_ids]
            for item in coverage:
                item.supporting_source_ids = [
                    source_id for source_id in item.supporting_source_ids if source_id in allowed_ids
                ]
            for action in actions:
                if action.type == "expand":
                    action.source_ids[:] = [source_id for source_id in action.source_ids if source_id in allowed_ids]
            actions = [action for action in actions if action.type != "expand" or action.source_ids]

        rationale = value.get("rationale")
        return cls(
            answerable=answerable,
            confidence=confidence,
            coverage=coverage,
            missing_information=_strings("missing_information", "missingInformation"),
            contradictions=_strings("contradictions"),
            supporting_source_ids=supporting_ids,
            next_actions=actions,
            rationale=rationale.strip() if isinstance(rationale, str) and rationale.strip() else None,
            valid=True,
        )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class IterationTrace:
    """Observable trace for one bounded agentic iteration."""

    iteration: int
    actions: List[Dict[str, Any]] = field(default_factory=list)
    retrieved_chunk_ids: List[str] = field(default_factory=list)
    new_chunk_ids: List[str] = field(default_factory=list)
    expanded_chunk_ids: List[str] = field(default_factory=list)
    candidate_count: int = 0
    evidence_ids: List[str] = field(default_factory=list)
    assessment: Optional[Dict[str, Any]] = None
    usage_total_tokens: int = 0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class AgenticSearchConfig:
    """Runtime limits and ranking controls for Agentic Search v2."""

    max_iterations: int = 3
    max_queries_per_iter: int = 10
    max_total_queries: int = 30
    token_budget: int = 4096
    top_k: int = 50
    rerank_limit: int = 15
    keyword_limit: int = 15
    candidate_limit: int = 200
    assessment_limit: int = 30
    evidence_limit: int = 20
    rrf_k: int = 60
    max_expansion_hops: int = 1
    max_expanded_chunks: int = 8
    no_progress_patience: int = 1
    max_per_document: int = 4

    def __post_init__(self) -> None:
        positive = {
            "max_iterations": self.max_iterations,
            "max_queries_per_iter": self.max_queries_per_iter,
            "max_total_queries": self.max_total_queries,
            "token_budget": self.token_budget,
            "top_k": self.top_k,
            "rerank_limit": self.rerank_limit,
            "keyword_limit": self.keyword_limit,
            "candidate_limit": self.candidate_limit,
            "assessment_limit": self.assessment_limit,
            "evidence_limit": self.evidence_limit,
            "rrf_k": self.rrf_k,
            "max_per_document": self.max_per_document,
        }
        invalid = [name for name, value in positive.items() if value <= 0]
        if invalid:
            raise ValueError(f"AgenticSearchConfig values must be positive: {', '.join(invalid)}")
        if self.max_expansion_hops < 0 or self.max_expanded_chunks < 0 or self.no_progress_patience < 0:
            raise ValueError("Expansion and no-progress limits cannot be negative")
